### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by ajhawkings** [YearInfo/YearInfo.github.io#13]
All I have to do is create a file called 404.html

**Comment by ajhawkings** [comment]
Broke

**Comment by ajhawkings** [comment]
ben good at style help kthx

**Comment by HandyHat** [comment]
Style needs to be moved to a separate css file to comply with csp, and bgcolour is deprecated and should also be moved to css

**Comment by ajhawkings** [comment]
kk i need to actually fix this

**Comment by HandyHat** [comment]
New 404 page looks pretty good - would it be possible to self-host the 404 image and the warning icon?
Neither of the places we are pulling from support CORS or provide ACAO headers, which means we can't use SRI

**Comment by ajhawkings** [comment]
Have done but im not sure the image appears on some browsers. Does the link need to be /icons/404.ico or icons/404.ico

**Comment by HandyHat** [comment]
Although we want the image to fill the screen without having to scroll - @benstockil
