### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by ajhawkings** [YearInfo/YearInfo.github.io#15]
now

**Comment by Epacnoss** [comment]
didnt mean to do that

**Comment by ajhawkings** [comment]
XD

**Comment by HandyHat** [comment]
PWA should be done - @ajhawkings can you check the icon on iOS?

**Comment by ajhawkings** [comment]
![AAA9F311-F463-4503-A02D-26A2C386D6D3](https://user-images.githubusercontent.com/70203823/108484565-dab53600-7293-11eb-8da9-e35d37964bcb.jpeg)
@HandyHat

**Comment by HandyHat** [comment]
Pog - now we just need the background colour set and then we should be good (cough @Epacnoss cough)

**Comment by ajhawkings** [comment]
Can be closed now @HandyHat?

**Comment by HandyHat** [comment]
Going to hold until #22 is well and truely done could we might have to change the border colour

**Comment by ajhawkings** [comment]
Kk np

**Comment by HandyHat** [comment]
Closed in dec082c
