### ISSUE TITLE
Better Favicon

### ISSUE THREAD

**Issue by HandyHat** [YearInfo/YearInfo.github.io#2]
Favicon looks bad on dark mode

**Comment by benstockil** [comment]
Possibly place it inside a coloured circle, that may help :/

**Comment by ajhawkings** [comment]
I might use the coloured logo like this (would need to remove background (in PowerPoint obvs))
![ECE36CA5-C69F-4D7D-B856-CD347532F119](https://user-images.githubusercontent.com/70203823/106390844-41a4a500-63e2-11eb-8916-5923efe4674e.jpeg)

**Comment by ajhawkings** [comment]
New one done - reopen if you don't like.
