### ISSUE TITLE
Look of website

### ISSUE THREAD

**Issue by HandyHat** [YearInfo/YearInfo.github.io#22]
Looks of the website need to be redone - right now the colour scheme clashes and we don't have any accessibility stuff

**Comment by HandyHat** [comment]
Copied from Discord:

Summary notes:
Background to be changed to be dark mode friendly
Background colours of text changed to be green (on left) and blue (on right) - same as cayman
Background of PWA (64, 128, 128)
PWA Theme Colour would be Cayman green
PWA Background colour would be dark mode friendly

**Comment by ajhawkings** [comment]
@Epacnoss ??????????

**Comment by Epacnoss** [comment]
doing it now

**Comment by Epacnoss** [comment]
See PR

**Comment by ajhawkings** [comment]
Poggers

**Comment by HandyHat** [comment]
Website looks cool but now we have accessibility issues :(
![image](https://user-images.githubusercontent.com/58530748/109427179-11542480-79e9-11eb-9670-e2cc3abc33a3.png)

**Comment by ajhawkings** [comment]
do we still have problems here?

**Comment by HandyHat** [comment]
Yes we need to change the background colour cause there isn't enough contrast

**Comment by ajhawkings** [comment]
Finito
