### ISSUE TITLE
No Script

### ISSUE THREAD

**Issue by HandyHat** [YearInfo/YearInfo.github.io#24]

**Comment by ajhawkings** [comment]
done poggg ?????

**Comment by HandyHat** [comment]
![image](https://user-images.githubusercontent.com/58530748/108608567-a63e9880-73bf-11eb-8a98-7c16efe74095.png)
yep agrundled

**Comment by ajhawkings** [comment]
pog
![Uploading image.png…]()

**Comment by ajhawkings** [comment]
@HandyHat Is this gonna happen often ie do i need to make it more helpful :P

**Comment by HandyHat** [comment]
Nah the only time I could possible see it happening is if someone is using internet explorer on high security, at which point it's a them problem soooo

**Comment by ajhawkings** [comment]
ahhh 😂
