### ISSUE TITLE
Add Contact Us

### ISSUE THREAD

**Issue by HandyHat** [YearInfo/YearInfo.github.io#26]
Email pog

**Comment by HandyHat** [comment]
@ajhawkings can you do this one? Should be as simple as adding a footer with like contact us: hello@l5info.live or something

**Comment by ajhawkings** [comment]
kk

**Comment by ajhawkings** [comment]
ok lmk what you think of it

**Comment by ajhawkings** [comment]
i tried footer but it looked horrible and we already have nice boxes and parsing and stuff

**Comment by ajhawkings** [comment]
hm im not too happy with it i might go back to a footer with copyright and stuff
