### ISSUE TITLE
Cloudflare Caching

### ISSUE THREAD

**Issue by HandyHat** [YearInfo/YearInfo.github.io#3]
Either we set up Github Actions to make an API request to purge cache every time, or we turn off Cloudflare Proxying

I don't think we lose anything by turning off proxying (and it would mean we don't go down if cloudflare goes down), but in the immortal words of @benstockil - it's more convienient, less fun

**Comment by benstockil** [comment]
Agreed; We're not hosting ourselves, so CF proxy isn't very useful. I'll turn it off when I get the chance

**Comment by benstockil** [comment]
Found a better solution: Created a Cloudflare site rule which completely bypasses the cache for www.lowerfifthinfo.tk.

**Comment by HandyHat** [comment]
Oh brilliant 👍
