### ISSUE TITLE
Form room change

### ISSUE THREAD

**Issue by ajhawkings** [YearInfo/YearInfo.github.io#34]
for my own reference layton t2 thurdays and firday

**Comment by ajhawkings** [comment]
is there like a remind me bot on gh

**Comment by HandyHat** [comment]
Are we adding this orrrrrr

**Comment by HandyHat** [comment]
OK so I tried adding a remind me bot but its broken rn

**Comment by ajhawkings** [comment]
comprendu

**Comment by ajhawkings** [comment]
fixed this maybe perhaps
