### ISSUE TITLE
Group Info title doesn't appear on some browsers

### ISSUE THREAD

**Issue by ajhawkings** [YearInfo/YearInfo.github.io#6]

**Comment by benstockil** [comment]
Could you be more specific as to which browsers are affected?

**Comment by ajhawkings** [comment]
Yeh basically it’s just appearing as white font on a white background (Firefox)

**Comment by ajhawkings** [comment]
Is the font colour set to black?

**Comment by ajhawkings** [comment]
@benstockil ^^

**Comment by ajhawkings** [comment]
@benstockil ^^^

**Comment by ajhawkings** [comment]
@benstockil ^^^^

**Comment by benstockil** [comment]
Firefox works fine for me

**Comment by benstockil** [comment]
Could you let me know which version of Firefox you're using?

**Comment by ajhawkings** [comment]
Text still appears white. 

Firefox 85.0 Windows 10 NOT LINUX

**Comment by ajhawkings** [comment]
![image](https://user-images.githubusercontent.com/70203823/106877023-3dbd9f00-66d0-11eb-83f5-960d4168a04c.png)

**Comment by ajhawkings** [comment]
Same on edge btw

**Comment by ajhawkings** [comment]
![image](https://user-images.githubusercontent.com/70203823/106877734-ff74af80-66d0-11eb-98e8-2f23aa309a28.png)

**Comment by ajhawkings** [comment]
Changed to 000000
