### ISSUE TITLE
Cross Browser Compat

### ISSUE THREAD

**Issue by HandyHat** [YearInfo/YearInfo.github.io#8]
We should probably use some automated testing suites to ensure there aren't other issues with different browsers and screen sizes

**Comment by ajhawkings** [comment]
GH education includes browserstack trial for a year. Am signing up.

**Comment by HandyHat** [comment]
Wait no I've already signed up @ajhawkings

**Comment by ajhawkings** [comment]
ok

**Comment by ajhawkings** [comment]
is there are team thing

**Comment by HandyHat** [comment]
Not sure
Putting this link here so it doesn't get forgotten: 
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Introduction

**Comment by HandyHat** [comment]
From what I can tell everything should work fine across modern browsers now (wow Apple is really annoying)

**Comment by ajhawkings** [comment]
We love Apple
