### ISSUE TITLE
Performance Metrics

### ISSUE THREAD

**Issue by HandyHat** [YearInfo/YearInfo.github.io#9]
We can use Lighthouse and other tests to ensure performance is good

**Comment by benstockil** [comment]
We could also use Web Vitals by Google.

**Comment by HandyHat** [comment]
Yep Lighthouse is also Google and measures web Vitals - https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Flowerfifthinfo.tk

**Comment by HandyHat** [comment]
Lighthouse-CI has been added, and I'll start to go through its findings

**Comment by ajhawkings** [comment]
https://developers.google.com/speed/pagespeed/insights/?url=l5info.live :/

**Comment by HandyHat** [comment]
Not sure why Pagespeed insights is reporting worse performance than Lighthouse-CI (link to reports is in Actions)
Now that #12 is done we can set up web vitals for measurements in the real world

**Comment by HandyHat** [comment]
Looks like Cloudflare Browser Insights measures Web Vitals but only for Chromium based browsers - good enough?

**Comment by ajhawkings** [comment]
no ff poggers

**Comment by ajhawkings** [comment]
how do i find the ci report

**Comment by HandyHat** [comment]
Lighthouse-CI can be found under Actions, click on a commit, lighthouse, run lighthous-ci, lines 32 and 34. Looks like adding web-vitals separately are a pain so we'll stick to Cloudflare insights for now. Closing this as performance seems good.
